const $=s=>document.querySelector(s);
const chars=[...'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzÄÖÜäöüß0123456789.,!?;:-_()[]+=/%&@€"\''];
const glyphs=new Map();let generatedSvg='';
function bindRange(id,out){const e=$(id),o=$(out);const f=()=>o.value=e.value;e.addEventListener('input',f);f()}bindRange('#size','#sizeOut');bindRange('#lineHeight','#lineOut');bindRange('#variation','#varOut');
function makeGrid(){const grid=$('#writingGrid');grid.innerHTML='';chars.forEach(ch=>{const box=document.createElement('div');box.className='glyph-box';const label=document.createElement('div');label.className='glyph-label';label.textContent=ch;const pad=document.createElement('div');pad.className='glyph-pad';const c=document.createElement('canvas');c.width=260;c.height=100;pad.appendChild(c);box.append(label,pad);grid.appendChild(box);setupCanvas(c,box,ch)})}
function setupCanvas(c,box,ch){const ctx=c.getContext('2d');ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=5;let drawing=false;const p=e=>{const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}};c.addEventListener('pointerdown',e=>{e.preventDefault();drawing=true;const q=p(e);ctx.beginPath();ctx.moveTo(q.x,q.y);c.setPointerCapture?.(e.pointerId)});c.addEventListener('pointermove',e=>{if(!drawing)return;e.preventDefault();const q=p(e);ctx.lineTo(q.x,q.y);ctx.stroke();box.classList.add('done');glyphs.set(ch,c.toDataURL('image/png'));updateCount()});c.addEventListener('pointerup',()=>drawing=false);c.addEventListener('pointercancel',()=>drawing=false)}
function updateCount(){$('#analysisText').textContent=`✓ ${glyphs.size} von ${chars.length} Zeichen gelernt.`}
makeGrid();
$('#clearWriting').onclick=()=>{glyphs.clear();makeGrid();updateCount()};
$('#downloadTemplate').onclick=downloadNotability;$('#downloadNotability').onclick=downloadNotability;$('#notabilityMode').onclick=downloadNotability;$('#webMode').onclick=()=>$('#writingGrid').scrollIntoView({behavior:'smooth',block:'center'});
function downloadNotability(){const cols=4,cellW=330,cellH=145,pad=35,rows=Math.ceil(chars.length/cols),w=cols*cellW+pad*2,h=rows*cellH+pad*2;let s=`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><rect width="100%" height="100%" fill="white"/><text x="35" y="28" font-family="Arial" font-size="18" font-weight="700">SchriftBot – Handschriftvorlage</text>`;chars.forEach((ch,i)=>{const x=pad+(i%cols)*cellW,y=pad+35+Math.floor(i/cols)*cellH;s+=`<rect x="${x}" y="${y}" width="${cellW-15}" height="${cellH-15}" rx="10" fill="white" stroke="#cbd5e1" stroke-width="2"/><text x="${x+12}" y="${y+24}" font-family="Arial" font-size="16" font-weight="700" fill="#64748b">${esc(ch)}</text><line x1="${x+12}" y1="${y+92}" x2="${x+${cellW-39}}" y2="${y+92}" stroke="#e2e8f0"/>`});s+='</svg>';downloadBlob(new Blob([s],{type:'image/svg+xml'}),'schriftbot-notability-vorlage.svg')}
function esc(x){return x.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')};function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('#sampleInput').addEventListener('change',e=>{const f=e.target.files?.[0];if(f&&f.type.startsWith('image/'))loadImage(f);else if(f)showUploadError('Bitte die Notability-Vorlage als PNG/JPG exportieren.')});
function loadImage(file){const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const c=$('#sampleCanvas'),ctx=c.getContext('2d');const scale=Math.min(1,1100/img.width);c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);ctx.drawImage(img,0,0,c.width,c.height);$('#previewWrap').classList.remove('hidden');$('#sampleStatus').textContent='✓ Bild geladen';$('#analysisText').textContent='✓ Bild geladen. Für das eigentliche Training bitte die Zeichen direkt in den Kästchen schreiben.'};img.src=r.result};r.readAsDataURL(file)}
function showUploadError(m){$('#previewWrap').classList.remove('hidden');$('#sampleStatus').textContent='⚠️ Upload';$('#analysisText').textContent=m}
$('#generate').onclick=generate;
function generate(){const text=$('#textInput').value;if(!text.trim()){alert('Bitte zuerst einen Text eingeben.');return}if(!glyphs.size){alert('Bitte zuerst Zeichen schreiben.');return}const size=+$('#size').value,line=+$('#lineHeight').value,variation=+$('#variation').value,maxW=1050;let x=30,y=size+20,body='';for(const ch of text){if(ch==='\n'){x=30;y+=size*line;continue}if(ch===' '){x+=size*.42;continue}const data=glyphs.get(ch);if(!data){x+=size*.55;continue}const w=Math.max(18,size*.58),h=size*1.05;body+=`<image href="${data}" x="${x.toFixed(1)}" y="${(y-h*.82).toFixed(1)}" width="${w.toFixed(1)}" height="${h.toFixed(1)}" preserveAspectRatio="xMidYMid meet"/>`;x+=w+variation*(Math.random()-.5);if(x>maxW-70){x=30;y+=size*line}}const height=Math.max(250,y+size*1.2);generatedSvg=`<svg xmlns="http://www.w3.org/2000/svg" width="${maxW}" height="${height}" viewBox="0 0 ${maxW} ${height}"><rect width="100%" height="100%" fill="white"/>${body}</svg>`;$('#paper').classList.remove('empty');$('#paper').innerHTML=generatedSvg;$('#downloadSvg').disabled=false;$('#downloadPng').disabled=false;$('#copyNotes').disabled=false;updateCount()}
$('#clearResult').onclick=()=>{$('#paper').classList.add('empty');$('#paper').innerHTML='<span>Noch kein Ergebnis</span>';generatedSvg='';$('#downloadSvg').disabled=true;$('#downloadPng').disabled=true;$('#copyNotes').disabled=true};$('#downloadSvg').onclick=()=>downloadBlob(new Blob([generatedSvg],{type:'image/svg+xml'}),'schriftbot-text.svg');$('#downloadPng').onclick=async()=>downloadBlob(await svgToPng(generatedSvg),'schriftbot-text.png');$('#copyNotes').onclick=async()=>{const b=await svgToPng(generatedSvg);if(navigator.clipboard?.write&&window.ClipboardItem)await navigator.clipboard.write([new ClipboardItem({'image/png':b})]);else downloadBlob(b,'schriftbot-notizen.png')};async function svgToPng(svg){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=img.width;c.height=img.height;c.getContext('2d').drawImage(img,0,0);c.toBlob(b=>b?resolve(b):reject(), 'image/png')};img.onerror=reject;img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg)})}
